### ISSUE TITLE
Implementation of XSQLDA_LENGTH macro is wrong

### ISSUE THREAD

**Issue by jairinhohw** [fernandobatels/rsfbclient#1]
The implementation of the XSQLDA_LENGTH [here](https://github.com/fernandobatels/rsfbclient/blob/master/src/statement.rs#L215) is returning the wrong length.

The code could be written as the following to return the correct value (and not panic on size < 1):
```rust
    /// Implementation of XSQLDA_LENGTH macro
    fn xsqlda_length(size: i16) -> usize {
        let n = (size - 1).max(0) as usize;

        std::mem::size_of::<XSQLDA>() + (std::mem::size_of::<XSQLVAR>() * n)
    }
```

**Comment by fernandobatels** [comment]
Seems nice. I don't realized this mistake. I will fixed.

You are using this lib? You can help the implementation?

**Comment by jairinhohw** [comment]
Did not use it, but was working on my own fbclient ffi crate to learn how to use ffi in rust.
Just recently i found out about this crate and read it to learn a bit more.

Will gladly help in the implementation once i make sense of what i am doing.

**Comment by fernandobatels** [comment]
> The implementation of the XSQLDA_LENGTH [here](https://github.com/fernandobatels/rsfbclient/blob/master/src/statement.rs#L215) is returning the wrong length.
> 
> The code could be written as the following to return the correct value (and not panic on size < 1):
> 
> ```rust
>     /// Implementation of XSQLDA_LENGTH macro
>     fn xsqlda_length(size: i16) -> usize {
>         let n = (size - 1).max(0) as usize;
> 
>         std::mem::size_of::<XSQLDA>() + (std::mem::size_of::<XSQLVAR>() * n)
>     }
> ```

You can give to me an utilization example where the size is < 1? I'm trying to make a test for cover this change...

**Comment by jairinhohw** [comment]
The only one would be when the size = 0, if you just want to know how many rows are in the result by the xsqlda.sqld, but the function actually allocates the same as size = 1, so it just avoids a panic if you use it wrong.

Maybe using  a size of type NonZeroU8 or something would be better.

**Comment by fernandobatels** [comment]
Done! Feel free to send more contributions.
