### ISSUE TITLE
[DOC-REQUEST] How to build the examples on Windows

### ISSUE THREAD

**Issue by silvioprog** [fernandobatels/rsfbclient#10]
Hi.

It would be nice some documentation for how to build the library (and examples) on Windows.

cheers

**Comment by fernandobatels** [comment]
You can help us with this? 

I saw your progress on the [telegram](https://t.me/rustlangbr) and I think that you can share with us writing on the README.md

**Comment by silvioprog** [comment]
Thanks a lot for sharing this project for the community! I'm going to help you to improve it. :-) 

Since we are going to automatize the building process (allowing to use static or shared library), this issue can be closed.
