### ISSUE TITLE
Should date_time still exist as a separate feature?

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#103]
Feature `date_time` seems to have become mandatory at some point.
Trying to build without it (`--no-default-features --feature linking` for example) fails for me.

I think I am not the only one: https://github.com/fernandobatels/rsfbclient/issues/102

I do not know why it was made optional in the first place

Should we add appropriate `cfg` guards so that `date_time` is optional again?
or should it just not be a separate feature (that is, get rid of the `cfg` guards and remove it from `Cargo.toml`s)

**Comment by fernandobatels** [comment]
I agree. It's okay to have the `date_time' feature, but we always need enable it.

The `Timestamp` is a basic type, you almost always use it.

**Comment by jairinhohw** [comment]
I think it will be better to remove the `date_time` feature flag, as being able to use dates and times is very important, and i don't see any reason to disable the feature.

**Comment by fernandobatels** [comment]
@dancingbug , do you want handle this implementation?
