### ISSUE TITLE
Can't cross compile from linux to win32

### ISSUE THREAD

**Issue by AndreiTS** [fernandobatels/rsfbclient#105]
I'm trying to create a win32 dll, I'm running:
cargo build --target=x86_64-pc-windows-gnu --release

and getting this error:
note: /usr/bin/x86_64-w64-mingw32-ld: cannot find -lfbclient

cargo.toml:
![image](https://user-images.githubusercontent.com/13489837/112523793-e2c63100-8d7d-11eb-9a0c-774bc87a8731.png)

lib.rs:
![image](https://user-images.githubusercontent.com/13489837/112523980-199c4700-8d7e-11eb-8038-246c3d422e0c.png)

**Comment by fernandobatels** [comment]
Please, try without default crate features: 
``
rsfbclient = { version="0.16.0", features = ["pure_rust"], default-features = false }
``

**Comment by AndreiTS** [comment]
Sorry, I said the wrong comand, actually it is:
cargo build --target=i686-pc-windows-gnu --release

I tried to build in a windows virtual machine to 32bits using platform i686-pc-windows-msvc but it's not working either.

Log from linux: https://pastebin.com/V0KfpCc0

**Comment by fernandobatels** [comment]
I tried compile one o examples here, with `i686-pc-windows-gnu`, and got the same error.  Unfortunately, my experience with cross compile is very superficial. 

You can help @jairinhohw ?

**Comment by jairinhohw** [comment]
Are you sure you disabled the default features of the `rsfbclient` crate? It should compile just fine with only the `pure_rust` feature.

**Comment by AndreiTS** [comment]
using cross solve it, thanks

**Comment by AndreiTS** [comment]
It's working on a computer but in the other it still don't work:
![image](https://user-images.githubusercontent.com/13489837/113325420-c763a480-92ee-11eb-9cb0-8258f00b9d24.png)
But I can work with that.

**Comment by jairinhohw** [comment]
Witch computer is the one that does not work? 32 or 64 bits? Are you using the `cross` tool?

Maybe it is related to [this](https://github.com/rust-lang/rust/issues/12859) issue, so it may just be unreliable to cross compile from a `x64` (64bits) machine to a `x86` (32bits).

**Comment by AndreiTS** [comment]
Both machines are 64bits, using cross
