### ISSUE TITLE
Example don't work.

### ISSUE THREAD

**Issue by almir-lima** [fernandobatels/rsfbclient#111]
Hi, i try made this example, but don't work in the new version 0.16.0.

https://medium.com/@luisfbatels/como-utilizar-o-banco-de-dados-firebird-com-a-linguagem-rust-812630dc0058

![image](https://user-images.githubusercontent.com/58075693/122627153-2af6a600-d084-11eb-8c6d-62dc57e734c4.png)
![image](https://user-images.githubusercontent.com/58075693/122627163-3c3fb280-d084-11eb-83de-6d1e50a33d93.png)

**Comment by almir-lima** [comment]
I managed to compile, but I'm getting error 111: connection refused, I will continue testing. 
thanks

**Comment by fernandobatels** [comment]
Please, share your code if you need more help.

You also can run [our examples](https://github.com/fernandobatels/rsfbclient/tree/master/examples) with the `cargo run --example` command.

**Comment by fernandobatels** [comment]
Looking your first print, the line 9 don't have the rows type that you want. 

If you only need a simple columns structs, you can use the tuples `Vec<(String, String)>`. [See here](https://github.com/fernandobatels/rsfbclient/blob/master/examples/embedded_select.rs#L32) an example.

**Comment by almir-lima** [comment]
Hi, thank for response.
The mode native is compatible with new version of firebird 4?

**Comment by fernandobatels** [comment]
Yes, I guess.

**Comment by fernandobatels** [comment]
I will test this as soon as possible

**Comment by fernandobatels** [comment]
[pt-br] Caso queiras um contato mais rápido e até trocar uma ideia sobre a lib, temos um grupo no telegram: https://t.me/rsfbclient

**Comment by almir-lima** [comment]
[pt-br] Obrigado vou participar, tenho um projeto novo e estava entre FB e MySql.
