### ISSUE TITLE
rsfbclient and rsfbclient-native are always recompiled

### ISSUE THREAD

**Issue by rfx77** [fernandobatels/rsfbclient#113]
when i do a cargo run, even if i changed nothing, rsfbclient and rsfbclient-native are always recompiled. i am using windows10.

this is caused by the build.rs file in rsfbclient-native line 17:

```
17:  println!("cargo:rerun-if-changed=src/tests/mod.rs");
```

There is no directory tests and no file tests/mod.rs so this always fires and causes the recompilation. when i comment this lie out everything works

**Comment by fernandobatels** [comment]
I will check this later. It appears to be a residue from the old project directory format.

Thanks for your report. If you wish, you can open a PR to fix this.
