### ISSUE TITLE
IntoParams, multiple usage.

### ISSUE THREAD

**Issue by nt202** [fernandobatels/rsfbclient#123]
Hello, how to use IntoParams more than once? (I am new to Rust)

<img width="650" alt="image" src="https://user-images.githubusercontent.com/20559489/181119037-a813806a-673c-482d-a78e-a49e7e3009a6.png">

```
error[E0252]: the name `ParamsType` is defined multiple times
  --> src/repo/authentic_repo.rs:30:10
   |
24 | #[derive(IntoParams, Message)]
   |          ---------- previous import of the type `ParamsType` here
...
30 | #[derive(IntoParams, Message)]
   |          ^^^^^^^^^^
   |          |
   |          `ParamsType` reimported here
   |          help: remove unnecessary import


24 | #[derive(IntoParams, Message)]
   |          ---------- previous import of the type `HashMap` here
...
30 | #[derive(IntoParams, Message)]
   |          ^^^^^^^^^^ `HashMap` reimported here
```

**Comment by fernandobatels** [comment]
Apparently this is a bug. I will fix. Please, isolate your structs with submodules for now. 

Example: 
```rust
pub mod mod1 {
 use rsfbclient::{prelude::*, FbError};
 pub struct UserExists...
}

pub mod mod2 {
 use rsfbclient::{prelude::*, FbError};
 pub struct PasswordCorrect...
}
```

**Comment by nt202** [comment]
Thank you :)

**Comment by fernandobatels** [comment]
`0.19.0` released, please check the new version

**Comment by nt202** [comment]
@fernandobatels, Thank you! It doesn't complain anymore, but I have a question, https://crates.io/crates/r2d2_firebird has not been updated?

**Comment by fernandobatels** [comment]
> https://crates.io/crates/r2d2_firebird has not been updated?

This crate is not building anymore with recents rust versions. I will check this tonight.
