### ISSUE TITLE
Fix r2d2 crate

### ISSUE THREAD

**Issue by fernandobatels** [fernandobatels/rsfbclient#125]
Fix de r2d2 build

_Originally posted by @nt202 in https://github.com/fernandobatels/rsfbclient/issues/123#issuecomment-1198181600_

**Comment by fernandobatels** [comment]
@nt202.

The [r2d2](https://crates.io/crates/r2d2_firebird) with `v0.19.0` is available now.

**Comment by nt202** [comment]
@fernandobatels, Thank you very much! :)
