### ISSUE TITLE
EventAlert

### ISSUE THREAD

**Issue by timanagement** [fernandobatels/rsfbclient#133]
Desde já quero parabenizar todos os envolvidos.  Existe algo para utilização de Firebird EventAlert no RUST com a rsfbclient ?

**Comment by fernandobatels** [comment]
> Desde já quero parabenizar todos os envolvidos. 

Obrigado

> Existe algo para utilização de Firebird EventAlert no RUST com a rsfbclient ?

Ainda não, mas posso implementar. Tens um caso de uso ou algum fonte/biblioteca de outra linguagem para servir de exemplo?

**Comment by timanagement** [comment]
Caro Fernando, criei um projeto console com .Net6 onde pode ser verificado a aplicação do **FbRemoteEvent** que pertence ao package **FirebirdSql.Data.FirebirdClient**

Juntei ao projeto demo a base de dados que criei para este exemplo.

Depois vou subir um projeto de conexão com RUST usando a tua crates e deixar público para ajudar quem desejar aprender RUST.


https://github.com/timanagement/console_fbevent

**Comment by fernandobatels** [comment]
Bacana. Vou verificar o material e estudar como trazer esse recurso para a crate.

**Comment by timanagement** [comment]
> Bacana. Vou verificar o material e estudar como trazer esse recurso para a crate.

Será muito bem vindo, pois permitirá, por exemplo, criar uma aplicação como serviço que execute determinada rotina acionada por um evento...

Se precisar de algo a mais, por favor não deixe de comunicar.

**Comment by fernandobatels** [comment]
Essa API de eventos do Firebird é bem desafiadora hehe. Até o momento fiquei levantando o material sobre o assunto e tudo o que precisarei implementar.

Você possui experiência com essa API a nível mais baixo? Pelo que andei vendo, preciso registrar o evento no fb e manter um loop esperando pela operação op_event.

**Comment by timanagement** [comment]
> 

Infelizmente não possuo experiências, além do uso, conforme descrito no manual o qual deixarei o link abaixo:

https://www.firebirdsql.org/file/documentation/papers_presentations/Power_Firebird_events.pdf


Outro link que possa te interessar para estudo, é sobre o node e de como eles usam o "fb-native.cpp" para lidar com eventos. 
Em especial, a partir da linha 226:

https://github.com/asfernandes/node-firebird-drivers/blob/master/packages/node-firebird-native-api/src/native/fb-native.cpp

**Comment by fernandobatels** [comment]
Sim. Consegui um material bom nos exemplos do firebird: 

https://github.com/FirebirdSQL/firebird/blob/master/examples/api/api16.c#L131

Ainda não tive uma grade evolução, mas aos poucos vai avançando.

**Comment by fernandobatels** [comment]
Travei no `isc_event_block`. Vou deixar essa issue de lado por um tempo. Mais tarde faço push do que estava sendo desenvolvido. Futuramente volto a atacar esse problema.

**Comment by timanagement** [comment]
Caro Fernando, vou buscando mais informações e, caso encontre, vou reportando aqui.  Desde já agradeço seus esforços.

**Comment by timanagement** [comment]
> Travei no `isc_event_block`. Vou deixar essa issue de lado por um tempo. Mais tarde faço push do que estava sendo desenvolvido. Futuramente volto a atacar esse problema.

Tem um repositório que implementou para uso com `node-firebird-libfbclient`.  Acredito que mostra o ponto onde vc disse ter travado. Veja os dois arquivos abaixo:

`fb-bindings-eventblock.h`
`fb-bindings-eventblock.cc`

https://github.com/xdenser/node-firebird-libfbclient/tree/master/src

**Comment by fernandobatels** [comment]
Opa. 

Aparentemente o `isc_event_block` não foi usado, vou tentar entender como o projeto usa o `isc_que_events` sem ele. 

Obrigado pelo material.

**Comment by fernandobatels** [comment]
Consegui passar o do `isc_event_block`. Resolvi recorrer ao [stackoverflow](https://stackoverflow.com/questions/74819667/rust-strings-and-c-variadic-functions) e deu boa. Logo subo novos commits.

**Comment by fernandobatels** [comment]
@timanagement , creio que deu certo. Você poderia testar a branch `firebird-events` e verificar se já lhe atende?

**Comment by timanagement** [comment]
> 

Seus esforços resultaram em sucesso.

Vou tentar descrever:

Na 1ª imagem está a configuração no seu exemplo para acessar o BD.

Na 2ª imagem está a Trigger criada para escutar o evento "SINC_USUARIO".

Na 3ª imagem está o que será executado, todas as vezes que o evento for escutado.

Na 4ª imagem está o resultado obtido.

![image](https://user-images.githubusercontent.com/104225732/215293726-8bff78f2-4e88-4e08-943a-81d4a75b6403.png)

![image](https://user-images.githubusercontent.com/104225732/215293759-b60b7170-37e4-47e3-9dcf-bffa14edc4bf.png)

![image](https://user-images.githubusercontent.com/104225732/215293852-6e5714a0-c466-4678-a212-748e0b742336.png)

![image](https://user-images.githubusercontent.com/104225732/215294171-91db15d8-0259-45e1-9c28-9c7a72a0ee7a.png)

**Comment by timanagement** [comment]
Não tenho palavras para te agradecer...

**Comment by fernandobatels** [comment]
Hehe, que bom que você curtiu.

Essa semana resolvo o que foi apontado na PR e solto uma nova versão da crate. Obrigado pela paciência e consideração.

**Comment by fernandobatels** [comment]
[Crate](https://crates.io/crates/rsfbclient) atualizada. Agora para usar o novo recurso basta usar a nova versão `0.23.0`

**Comment by timanagement** [comment]
> [Crate](https://crates.io/crates/rsfbclient) atualizada. Agora para usar o novo recurso basta usar a nova versão `0.23.0`

Perfeito.  Obrigado mais uma vez.
