### ISSUE TITLE
client library is needed with pure_rust?

### ISSUE THREAD

**Issue by awunnenb** [fernandobatels/rsfbclient#144]
Why is the libfbclient needed when using rsfbclient::builder_pure_rust

Linux Debian:
./rsfbclient-test: error while loading shared libraries: libfbclient.so.2: cannot open shared object file: No such file or directory

Is it possible to use rsfbclient on the macOS Intel with pure_rust?

Error message when compiling: 
 = note: ld: library not found for -llibfbclient
          clang: error: linker command failed with exit code 1

**Comment by jairinhohw** [comment]
You need to disable the default features. Example:
```toml
rsfbclient = { version = "0.23.0", default_features = false, features = ["pure_rust"] }
```

**Comment by awunnenb** [comment]
thank you very much!!!
