### ISSUE TITLE
sql error -923 when I try connecting to db.

### ISSUE THREAD

**Issue by DmitryNX** [fernandobatels/rsfbclient#145]
I get the next error:
`sql error -923 Connection rejected by remote interface`

I have the next code:
OS: Windows 10

Cargo.toml
```
[dependencies]
rsfbclient = { version = "0.23.0", default_features = false, features = ["dynamic_loading"] }
```

main.rs
```
fn connect() -> Result<(), FbError> {
    let mut conn = rsfbclient::builder_native()
        .with_dyn_load("./fbclient.dll")
        .with_remote()
        .host("localhost")
        .db_name("D:/awesome.fdb")
        .user("SYSDBA")
        .pass("masterkey")
        .connect()?;

    // ...
}
```

**Comment by fernandobatels** [comment]
This sounds like a firebird configuration issue.

Please, check:
- if your `./fbclient.dll` is compatible 32bits/64bits with your server;
- version of your client `.dll` and your firebird server;
- security/auth firebird options: https://stackoverflow.com/a/30397408/9209351;
- try connect with `with_dyn_link` variant;

**Comment by DmitryNX** [comment]
I have checked all your points, but it didn`t give me any success.

But I did not say You that my task is connecting to InterBase. 
Also I noticed, from time to time, my code works perfectly and I get a result. 
And, finally, I want to say it is possible to connect to InterBase by Firebird client (for example in C++/Qt there is plugin IBASE to do it).
 
Is it probably some mistakes in the crate?

**Comment by fernandobatels** [comment]
> Is it probably some mistakes in the crate?

Maybe, but I'm going to need some reproducible situation. 

Can you share your project code or an example that build and reproduce your problem?

**Comment by DmitryNX** [comment]
A minimal example:

Cargo.toml
```
[dependencies]
rsfbclient = { version = "0.23.0", default_features = false, features = ["dynamic_loading"] }
```


main.rs
```
use rsfbclient::{FbError, Queryable};

fn main() -> Result<(), FbError> {
    let mut conn = rsfbclient::builder_native()
        .with_dyn_load("./fbclient.dll")
        .with_remote()
        .host("localhost")
        .port(3050)
        .db_name("D:\\awesome.fdb")
        .user("SYSDBA")
        .pass("masterkey")
        .connect()?;      
    
    let response: Vec<(String,)> = conn.query("SELECT * FROM my_table", ())?;
    
    println!("Rows count: {}", response.len());
    
    Ok(())
}

```

When I call the `connect()` function I catch the error, also I notice in `firebird.log` file at this moment the next error:
```
INET/inet_error: read errno = 10054
```

If I try using Firebird server instead Firebase server then I take the next error:
```
Error unsupported on-disk structure for file D:\\awesome.fdb found 13.1, support 12.0
```

**Comment by fernandobatels** [comment]
Please, provide your firebird/firebase version.

**Comment by DmitryNX** [comment]
> Please, provide your firebird/firebase version.

Firebird 3
Firebase 2009

**Comment by fernandobatels** [comment]
> But I did not say You that my task is connecting to InterBase.

I think that the fbclient is not full compatible with interbase in some versions. 

> If I try using Firebird server instead Firebase server then I take the next error:
> Error unsupported on-disk structure for file D:\\awesome.fdb found 13.1, support 12.0

Please, try use a full firebird 3 environment, with server, dll and fdb on firebird 3. Maybe your fdb file was generated on interbase or with a old version of firebird.
