### ISSUE TITLE
Continuing the GitHub Actions setup

### ISSUE THREAD

**Issue by fernandobatels** [fernandobatels/rsfbclient#25]
* [ ] Next steps
  * [ ] Run test with Firebird 2.5-ss, 3.0 and 4.0
  * [ ] Run on Windows
  * [ ] Run on Linux/ARM
  * [ ] Run on Linux/ARM/LittleEndian
  * [ ] Release workflow to crates.io and rust docs.
* [ ] Status
  * [x] Coverage failing on cc linking (needs help...)
  * [ ] Next steps on further PRs
-------
Continuation of #24

**Comment by fernandobatels** [comment]
For you @juarezr ;)

**Comment by juarezr** [comment]
Any clue about this [failure](https://github.com/fernandobatels/rsfbclient/runs/959232114?check_suite_focus=true) ?

Anybody can help me figuring out what's failing in the build?

**Comment by jairinhohw** [comment]
I couldn't find out the problem, but for now you can build with the `dynamic_loading` for it to work
