### ISSUE TITLE
Parameters and querys

### ISSUE THREAD

**Issue by fernandobatels** [fernandobatels/rsfbclient#3]
Now, the lib only can execute a simple queries without parameters, and this is not ok. So:

- [ ] add support for parameters in querys like the https://github.com/rusqlite/rusqlite
- [ ] the "query_simple" and "execute_simple" approaches will be removed
- [ ] Use the no_params! macro, or similar, instead

**Comment by fernandobatels** [comment]
@jairinhohw, you have any suggestions or comments about this?

**Comment by jairinhohw** [comment]
I'm working on this on my test implementation. Right now i have a working implementation of the output xsqlda that receives the type information from the database and allocates / coerces the date to known types to make impossible to try to interpret a varchar as a number for example, and i am now working to use a similar logic to implement the input xsqlda (parameters).

I will port it to this lib when i get it working.

**Comment by jairinhohw** [comment]
The result will look something like this:

```rust
let mut cursor = stmt.query(("coffe", 45))?; // Two parameters

while let Some(row) = cursor.fetch()? {
    let row: (Option<i32>, String, f64) = row; // Three columns of data

    println!("{:?}\n", row);
}
```

As of now, i got the fetch return working.

**Comment by fernandobatels** [comment]
> I'm working on this on my test implementation. Right now i have a working implementation of the output xsqlda that receives the type information from the database and allocates / coerces the date to known types to make impossible to try to interpret a varchar as a number for example, and i am now working to use a similar logic to implement the input xsqlda (parameters).

This is a new level for the lib, hehe. The idea of use the database type instead the code specified type is amazing. 

> I will port it to this lib when i get it working.

Nice.

**Comment by fernandobatels** [comment]
> The result will look something like this:

I'm curious to see how you managed to implement this

**Comment by fernandobatels** [comment]
So, I will wait for you implementation since you are progressing better than me. If I can help with something, I'm here.

**Comment by fernandobatels** [comment]
I will pub a new lib version on the crates site with yours contributions.
