### ISSUE TITLE
Readme enhancements

### ISSUE THREAD

**Issue by fernandobatels** [fernandobatels/rsfbclient#40]
How we can improve our readme.md for show the features and documentation? Any ideas? @jairinhohw @juarezr @mariuz 

I think we don't need more the firebird references.

**Comment by jairinhohw** [comment]
I think we must explain the cargo features and how / when to use them in the readme, as there is no documentation in them at the moment.
Maybe create a new issue to review the features names too.

**Comment by jairinhohw** [comment]
Something like:

# Features
All features can be used at the same time if needed.

### `linking`
Will use the dynamic library of the official `fbclient` at runtime and compiletime.
Used in systems where there is already a firebird client installed and configured.
### `dynamic_loading`
Can find the official `fbclient` native library by path at runtime, does not need the library at compiletime.
Useful when you need to build in a system without a firebird client installed.
### `pure_rust`
Uses a pure rust implementation of the firebird wire protocol, does not need the library at all.
Useful for cross-compilation and allow a single binary to be deployed without needing to install the firebird client.

**Comment by juarezr** [comment]
@fernandobatels,

Maybe we should promote the strong points of using 
FirebirdSQL with Rust in a section "Why you should use it!"  before the details of  "How to use it".

We can write a brief about the best selling points like:
- A lean database server feature rich and with full SQL compliance embedded into 'your' app that are more powerful and faster than SQLite.
- Pure ( no unsafe ) Rust connecting to FirebirdSQL.
- etc...

**Comment by fernandobatels** [comment]
> @fernandobatels,
> 
> Maybe we should promote the strong points of using
> FirebirdSQL with Rust in a section "Why you should use it!" before the details of "How to use it".
> 
> We can write a brief about the best selling points like:
> 
>     * A lean database server feature rich and with full SQL compliance embedded into 'your' app that are more powerful and faster than SQLite.
> 
>     * Pure ( no unsafe ) Rust connecting to FirebirdSQL.
> 
>     * etc...

This is nice. But to affirm "faster than SQLite" we need some benchmarks
