### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by AndreiTS** [fernandobatels/rsfbclient#45]
How can I specify a encoding to connect to a database?

Example in python:

```
conn  = fdb.connect(
    user='SYSDBA',
    password='masterkey',
    database='/firebird/data/BASE.FDB',
    charset='win1252'
)
```

**Comment by jairinhohw** [comment]
Rust `String` type is `UTF-8` encoded, so the connection needs to be `UTF-8` encoded to allow to store the data from the database correctly in rust `String`. As such, this library only connects using `UTF-8` charset (It can connect to databases with data stored in other charsets, but they are converted to be sent / received in `UTF-8`)

**Comment by AndreiTS** [comment]
I don't think it's working:

Table:
![image](https://user-images.githubusercontent.com/13489837/92278070-c38fb100-eeca-11ea-94a4-f17615bdd8ac.png)

Output: 
Codigo: 000201, Grupo: BEBIDAS
Codigo: 000301, Grupo: HIGIENE E LIMP
Codigo: 000401, Grupo: CONGELADOS
Codigo: 000701, Grupo: CONSERVAS
Codigo: 000801, Grupo: TEMPEROS
Codigo: 000901, Grupo: MOLHOS
Codigo: 001001, Grupo: OLEOS
Codigo: 001401, Grupo: CEREAIS
Codigo: 001701, Grupo: PAOS E BOLOS
Codigo: 002101, Grupo: LATICINIOS
Codigo: 002401, Grupo: ACOUGUE
Codigo: 002701, Grupo: LIMPEZA
Codigo: 002801, Grupo: UTILITARIOS
Codigo: 002901, Grupo: RACOES PET
Codigo: 003101, Grupo: HORTIFRUTI
Codigo: 003301, Grupo: BOMBONIERE
Codigo: 003401, Grupo: CIGARROS
Codigo: 003501, Grupo: DIVERSOS
Codigo: 003701, Grupo: SALG. E BISCOIT
Codigo: 003801, Grupo: PICOLES E SORVE
Codigo: 003902, Grupo: ENLATADOS
Codigo: 004003, Grupo: ERVA - MATE
Codigo: 004103, Grupo: MERCEARIA
Codigo: 004202, Grupo: PADARIA
Codigo: 004304, Grupo: RECARGA`

But, if I change "PAO" to "PÃO" it stops when it reaches this record:

![image](https://user-images.githubusercontent.com/13489837/92278209-1d907680-eecb-11ea-87e2-74e33544d647.png)

Output: 
![image](https://user-images.githubusercontent.com/13489837/92278242-313bdd00-eecb-11ea-9567-c0a446745b9e.png)

Code: https://gist.github.com/AndreiTS/cadb9475a8ac2065ca31def23d7fde05

**Comment by jairinhohw** [comment]
Can you try to print the error message? I don't see any in the output.

**Comment by AndreiTS** [comment]
I think this error come from here:

https://github.com/fernandobatels/rsfbclient/blob/61a89e5996f0b2ff2891bcb7e838147e942f3d43/rsfbclient-native/src/row.rs#L143

**Comment by jairinhohw** [comment]
What firebird version are you using?
Didi you set the encoding in the DBeaver configuration?
![image](https://user-images.githubusercontent.com/7423996/92281009-14a2a380-eed1-11ea-866b-2723e88ac948.png)

I've tried writing `Pão teste PÃO áã ç` using dbeaver with `win1252` encoding and was able to read it in rust.

**Comment by AndreiTS** [comment]
Firebird 2.5.9
![image](https://user-images.githubusercontent.com/13489837/92284641-ca252500-eed8-11ea-9dfe-500766726d5a.png)

**Comment by AndreiTS** [comment]
win1252 is different from WIN1252?

**Comment by jairinhohw** [comment]
Should be the same, not really sure what is wrong

**Comment by AndreiTS** [comment]
I tested with another database (driver: win1252) and the result is the same:

Table:
![image](https://user-images.githubusercontent.com/13489837/92304184-0183e800-ef52-11ea-8ea4-f360600cf20b.png)
![image](https://user-images.githubusercontent.com/13489837/92304190-0f396d80-ef52-11ea-9f93-af9b26db8ae7.png)

It only works if a set the driver to UTF8 and change the text again:

Driver set to UTF8:
![image](https://user-images.githubusercontent.com/13489837/92304198-2f692c80-ef52-11ea-9335-85b73a4a2af8.png)
Fixed text:
![image](https://user-images.githubusercontent.com/13489837/92304209
![image](https://user-images.githubusercontent.com/13489837/92304215-50318200-ef52-11ea-9273-0aa8b935c1f5.png)
-460f8380-ef52-11ea-99b9-a2bb337fbb36.png)

**Comment by AndreiTS** [comment]
The charset of "EMPCADASTRO" is None. If the charset is set to win1252, like this:
![image](https://user-images.githubusercontent.com/13489837/92304296-144aec80-ef53-11ea-836b-fd2325ae4192.png)
It woks.

I tried to change the charset of other columns but it's not working:

I tried this: https://firebirdsql.org/refdocs/langrefupd25-ddl-charset.html
and this command: 

ALTER TABLE TB_CLIENTE ALTER COLUMN EMPCADASTRO TYPE VARCHAR(20) CHARACTER SET WIN_1252;

But the charset still is None.

Do you know if there is another way to get this working?

**Comment by AndreiTS** [comment]
I made some changes to the crate rsfbclient-native (rows.rs) in order to work with columns that have win1252 text but are set to the charset none:

![image](https://user-images.githubusercontent.com/13489837/92304691-94268600-ef56-11ea-8739-1f78f1edd090.png)

![image](https://user-images.githubusercontent.com/13489837/92304669-69d4c880-ef56-11ea-81da-f0ec1fa36645.png)

Disclaimer: I learned rust last week is this is a "gambiarra", maybe you can do something better with it

**Comment by AndreiTS** [comment]
Result:
![image](https://user-images.githubusercontent.com/13489837/92304737-f7181d00-ef56-11ea-8321-4e44237f88e4.png)
![image](https://user-images.githubusercontent.com/13489837/92304742-0303df00-ef57-11ea-85ad-8db9a6688694.png)

**Comment by fernandobatels** [comment]
> The charset of "EMPCADASTRO" is None. If the charset is set to win1252, like this:
> ![image](https://user-images.githubusercontent.com/13489837/92304296-144aec80-ef53-11ea-836b-fd2325ae4192.png)
> It woks. (encoding is specified to win1252)
> 
> I tried to change the charset of other columns but it's not working:
> 
> I tried this: https://firebirdsql.org/refdocs/langrefupd25-ddl-charset.html
> and this command:
> 
> ALTER TABLE TB_CLIENTE ALTER COLUMN EMPCADASTRO TYPE VARCHAR(20) CHARACTER SET WIN_1252;
> 
> But the charset still is None.
> 
> Do you know if there is another way to get this working?

You cannot change a the charset of numeric columns, because they don't have it. So the charset always will be 'None'

**Comment by AndreiTS** [comment]
I was trying to change the charset of a varchar column: 
![image](https://user-images.githubusercontent.com/13489837/92305102-604d5f80-ef5a-11ea-9a52-6dbe29ff23ee.png)

**Comment by fernandobatels** [comment]
@AndreiTS , maybe the problem is your terminal encoding. You can make a test writing this data directly to a text file?

**Comment by AndreiTS** [comment]
rsfbclient 0.8.0 with my changes: https://gist.github.com/AndreiTS/afc2938868a4e657da2cc92f1c450605
rsfbclient 0.9.0: 
![image](https://user-images.githubusercontent.com/13489837/92305262-09e12080-ef5c-11ea-8e17-150a981fa361.png)

The code is the same, I just changes the dependencies

**Comment by fernandobatels** [comment]
@AndreiTS , I make [this test](https://github.com/fernandobatels/rsfbclient/commit/2cdc4c9881629ec8abefa7f3c3ff21619365492e) for check some charsets. You can run in your environment?

**Comment by fernandobatels** [comment]
> rsfbclient 0.8.0 with my changes: https://gist.github.com/AndreiTS/afc2938868a4e657da2cc92f1c450605
> rsfbclient 0.9.0:
> ![image](https://user-images.githubusercontent.com/13489837/92305262-09e12080-ef5c-11ea-8e17-150a981fa361.png)
> 
> The code is the same, I just changes the dependencies

Please, post here the backtrace(RUST_BACKTRACE=1 cargo run). I think the problem is in the column name and not in the content.

**Comment by AndreiTS** [comment]
I modified the test to connect to the same database:
![image](https://user-images.githubusercontent.com/13489837/92305424-9d672100-ef5d-11ea-85f4-ad565bd8e932.png)

Test with rsfbclient 0.9.0 (no changes):  https://gist.github.com/AndreiTS/5bc866b90d9bdff178ff33ce08fe7f7e
Test with rsfbclient 0.9.0 (with the changes that I did, they break utf8 text :D): https://gist.github.com/AndreiTS/f9628c0f50092f555825b6e270647ae6

**Comment by AndreiTS** [comment]
> > rsfbclient 0.8.0 with my changes: https://gist.github.com/AndreiTS/afc2938868a4e657da2cc92f1c450605
> > rsfbclient 0.9.0:
> > ![image](https://user-images.githubusercontent.com/13489837/92305262-09e12080-ef5c-11ea-8e17-150a981fa361.png)
> > The code is the same, I just changes the dependencies
> 
> Please, post here the backtrace(RUST_BACKTRACE=1 cargo run). I think the problem is in the column name and not in the content.

https://gist.github.com/AndreiTS/6f2b9aadf1824b212021798cdf19aa31

**Comment by fernandobatels** [comment]
> I think the problem is in the column name and not in the content.

Forget. The problem is even with the content.

**Comment by fernandobatels** [comment]
> Test with rsfbclient 0.9.0 (no changes): https://gist.github.com/AndreiTS/5bc866b90d9bdff178ff33ce08fe7f7e

So, with cast works fine. 

You can share your database(not all tables) + table schema/DDL?

**Comment by AndreiTS** [comment]
> > Test with rsfbclient 0.9.0 (no changes): https://gist.github.com/AndreiTS/5bc866b90d9bdff178ff33ce08fe7f7e
> 
> So, with cast works fine.
> 
> You can share your database(not all tables) + table schema/DDL?

https://gist.github.com/AndreiTS/51cc172e5b4484b3e7886829b057b271

**Comment by fernandobatels** [comment]
> > > Test with rsfbclient 0.9.0 (no changes): https://gist.github.com/AndreiTS/5bc866b90d9bdff178ff33ce08fe7f7e
> > 
> > 
> > So, with cast works fine.
> > You can share your database(not all tables) + table schema/DDL?
> 
> https://gist.github.com/AndreiTS/51cc172e5b4484b3e7886829b057b271

I runned this tests and works fine. You have access to a firebird 3 server?

**Comment by AndreiTS** [comment]
Did you run the test or the code in the gist? Yes, I have access to a fb3 server

**Comment by fernandobatels** [comment]
> Did you run the test or the code in the gist? Yes, I have access to a fb3 server

Yes, but I'm running into a linux environment

**Comment by AndreiTS** [comment]
I'm too, Pop OS 20.04

**Comment by fernandobatels** [comment]
> I'm too, Pop OS 20.04

I thought it was a windows environment, because of "CREATE DATABASE 'localhost:D:\usuarios\Administrador5\Desktop\BASE.FDB''. 

You can test your gist into a recreated(whit your sql script) database?

**Comment by AndreiTS** [comment]
I copied the database to a Windows Server to export it using IBExpert, but all the code I ran in linux

**Comment by fernandobatels** [comment]
If you are running the firebird into a windows server and you client into a linux environment, maybe they have some of conflicts. Some people are recommending to use the ISO88591 instead: https://www.projetoacbr.com.br/forum/topic/29433-lazarus-firebird-caracteres-estranhos/

You can make a test with a full linux environment ?

**Comment by AndreiTS** [comment]
I'm running firebird inside a docker container:

![image](https://user-images.githubusercontent.com/13489837/92306583-94c71880-ef66-11ea-8bb0-7fe070e4ca57.png)

I uploaded the database and the code to google drive to make things easier:
https://drive.google.com/drive/folders/1rt1OQcg28cYY6tr5VDtybqQm4eYP6b4H

**Comment by fernandobatels** [comment]
> I'm running firebird inside a docker container:
> 
> ![image](https://user-images.githubusercontent.com/13489837/92306583-94c71880-ef66-11ea-8bb0-7fe070e4ca57.png)
> 
> I uploaded the database and the code to google drive to make things easier:
> https://drive.google.com/drive/folders/1rt1OQcg28cYY6tr5VDtybqQm4eYP6b4H

Now i can reproduce the problem hehe.

**Comment by fernandobatels** [comment]
> I'm running firebird inside a docker container:
> 
> ![image](https://user-images.githubusercontent.com/13489837/92306583-94c71880-ef66-11ea-8bb0-7fe070e4ca57.png)
> 
> I uploaded the database and the code to google drive to make things easier:
> https://drive.google.com/drive/folders/1rt1OQcg28cYY6tr5VDtybqQm4eYP6b4H

For now, you can cast the columns to a UTF8 and this will work. I will investigate what we can do

**Comment by fernandobatels** [comment]
I think this is a charset/collation problem of database. I make a new column with UTF8 and when I updated the firebird return a error:
```
ALTER TABLE C000017 ADD GRUPOALT2 Varchar(30) CHARACTER SET UTF8;
commit;
UPDATE C000017 a SET a.GRUPOALT2 = CAST(a.GRUPO as varchar(30) CHARACTER SET utf8);
```
The error:
```
SQL Message : -104
Invalid token

Engine Code    : 335544849
Engine Message :
Malformed string
```

Has anyone ever experienced this? @jairinhohw @juarezr

**Comment by jairinhohw** [comment]
So, i think i understood the problem.
The problem is that the column you are trying to access has a charset set no 'NONE', so to the firebird database, the column is basically the same as a binary column, it does not know that the column is `win1252` encoded, so it cannot convert to `utf8` to send correctly to the client.
This can be seen when you set the `utf8` encoding in the dbeaver and got nonsensical data in the print, this would not happend if the firebird knew the charset of the column, as it would convert it to `utf8`and would display fine in dbeaver and rust.

**Comment by AndreiTS** [comment]
> So, i think i understood the problem.
> The problem is that the column you are trying to access has a charset set no 'NONE', so to the firebird database, the column is basically the same as a binary column, it does not know that the column is `win1252` encoded, so it cannot convert to `utf8` to send correctly to the client.
> This can be seen when you set the `utf8` encoding in the dbeaver and got nonsensical data in the print, this would not happend if the firebird knew the charset of the column, as it would convert it to `utf8`and would display fine in dbeaver and rust.

Yes exactly. In python with the "fdb" package you can force a charset by passing .charset() in the connection property. I think this crate could have something similar

**Comment by AndreiTS** [comment]
https://fdb.readthedocs.io/en/v2.0/reference.html#fdb.connect

source: https://github.com/FirebirdSQL/fdb

**Comment by jairinhohw** [comment]
> I think this is a charset/collation problem of database. I made a new column with UTF8 and when I updated the firebird return an error:
> 
> ```
> ALTER TABLE C000017 ADD GRUPOALT2 Varchar(30) CHARACTER SET UTF8;
> commit;
> UPDATE C000017 a SET a.GRUPOALT2 = CAST(a.GRUPO as varchar(30) CHARACTER SET utf8);
> ```
> 
> The error:
> 
> ```
> SQL Message : -104
> Invalid token
> 
> Engine Code    : 335544849
> Engine Message :
> Malformed string
> ```
> 
> Has anyone ever experienced this? @jairinhohw @juarezr

If the `GRUPO` column was not `UTF8` You cant need to convert to the original charset (probably `win1252` in this case) in the cast, not to `UTF8`.

**Comment by jairinhohw** [comment]
But the easier solution would be to use dbeaver to set the column charset to `win1252` for all text columns that need it.

**Comment by jairinhohw** [comment]
You select like this too:
`SELECT cast(grupo AS varchar(30) CHARACTER SET WIN_1252) FROM C000017;`

**Comment by jairinhohw** [comment]
If you want to convert the column to a new format:
```sql
ALTER TABLE C000017 ADD GRUPOALT2 Varchar(30) CHARACTER SET UTF8;
UPDATE C000017 a SET a.GRUPOALT2 = CAST(a.GRUPO as varchar(30) CHARACTER SET WIN_1252);
```
After this, you can delete the old column and rename the new one with the old name

**Comment by AndreiTS** [comment]
The problem is that the database is very big, and the program that is going to use it doesn't work with UTF8 (it's an delphi 7 application). I will try your suggestions

**Comment by jairinhohw** [comment]
> The problem is that the database is very big, and the program that is going to use it doesn't work with UTF8 (it's an delphi 7 application). I will try your suggestions

You can cast it on select only for the rust client, so nothing will be changed.
`SELECT cast(grupo AS varchar(30) CHARACTER SET WIN_1252) FROM C000017;`

**Comment by jairinhohw** [comment]
The conversion will work as long as you create a new column with the `WIN_1252` charset, which will not change anything in practice, except that the firebird now knows the column is `WIN_1252` encoded.

**Comment by fernandobatels** [comment]
> > So, i think i understood the problem.
> > The problem is that the column you are trying to access has a charset set no 'NONE', so to the firebird database, the column is basically the same as a binary column, it does not know that the column is `win1252` encoded, so it cannot convert to `utf8` to send correctly to the client.
> > This can be seen when you set the `utf8` encoding in the dbeaver and got nonsensical data in the print, this would not happend if the firebird knew the charset of the column, as it would convert it to `utf8`and would display fine in dbeaver and rust.
> 
> Yes exactly. In python with the "fdb" package you can force a charset by passing .charset() in the connection property. I think this crate could have something similar

Yesterday I made some tests changing the [charset used](https://github.com/fernandobatels/rsfbclient/blob/master/rsfbclient-native/src/connection.rs#L92), but it also didn't work

**Comment by fernandobatels** [comment]
> The conversion will work as long as you create a new column with the `WIN_1252` charset, which will not change anything in practice, except that the firebird now knows the column is `WIN_1252` encoded.

In fact, we always must use a default charset instead of none. But, I think that is a common problem(database with 'none' charset).

**Comment by fernandobatels** [comment]
Using the pure_rust feature didn't work either

**Comment by fernandobatels** [comment]
@AndreiTS, please. Test [this commit](https://github.com/fernandobatels/rsfbclient/commit/676f8cafacce09e9ff68a6abe2cc21bbdde21b5c)

**Comment by fernandobatels** [comment]
I'm working in the charset support, but your case(the C000017 table) are working now

**Comment by AndreiTS** [comment]
> @AndreiTS, please. Test [this commit](https://github.com/fernandobatels/rsfbclient/commit/676f8cafacce09e9ff68a6abe2cc21bbdde21b5c)

It's working, thank you

![image](https://user-images.githubusercontent.com/13489837/92327133-f8684900-f02d-11ea-8b27-446072984ee3.png)

**Comment by fernandobatels** [comment]
You can make insert/update tests? I'm working in this right now.

**Comment by AndreiTS** [comment]
It's saves in utf8:

![image](https://user-images.githubusercontent.com/13489837/92327538-cd332900-f030-11ea-9075-36a3d3ef86d4.png)

![image](https://user-images.githubusercontent.com/13489837/92327558-e2a85300-f030-11ea-9166-c929a5420f2f.png)

**Comment by AndreiTS** [comment]
DBeaver:

UTF8:
![image](https://user-images.githubusercontent.com/13489837/92327588-197e6900-f031-11ea-851c-6ec84e1ba3ec.png)
WIN1252:
![image](https://user-images.githubusercontent.com/13489837/92327601-2ac77580-f031-11ea-9c36-9482ba41d405.png)

**Comment by fernandobatels** [comment]
@AndreiTS [this commit](https://github.com/fernandobatels/rsfbclient/commit/9a1dd8a11f67a0ee3243839b460c2c6ba09e5032) will fix the params problem.

**Comment by AndreiTS** [comment]
> @AndreiTS [this commit](https://github.com/fernandobatels/rsfbclient/commit/9a1dd8a11f67a0ee3243839b460c2c6ba09e5032) will fix the params problem.

![image](https://user-images.githubusercontent.com/13489837/92328636-8c3f1280-f038-11ea-853b-c83e20ccda18.png)
 All good

**Comment by fernandobatels** [comment]
I completed the implementation and will open a PR to review and merge this fixes into the master.

**Comment by fernandobatels** [comment]
@AndreiTS , thanks for your issue. Now the charset support are officially released: https://github.com/fernandobatels/rsfbclient/releases/tag/v0.10.0
