### ISSUE TITLE
Document initial questions and answers about Firebird client implementations

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#62]
This issue can be a temporary place for questions and answers about Internals of Firebird clients (including our own `rsfbclient-rust`) that are not covered clearly by existing links in `README.md` or `CONTRIBUTING.md`
 
For starters:
  

- [x]  What is a high level overview of the flow of wire protocol and `BLR` on client and server sides of the FB remote code?
- [x] In `rsfbclient-rust` are there any choices being made about communicating with the remote side? or is the wire protocol so tightly specified that there's really only ever one valid sequence of interaction? Does `rsfbclient-rust` try to match the choices of some other client?
- [ ] In Firebird source, what parts of their code turn into `fbclient.so/dll` (in new and in older versions)? what is the exact relationship between standard `ibase.h` and the Firebird Remote / YValve source?

**Comment by jairinhohw** [comment]
>     * [ ]   What is a high level overview of the flow of wire protocol and `BLR` on client and server sides of the FB remote code?

The wire protocol works by sending / receiving "messages", which are based on the [XDR] format.
The list and definition of most messages used can be found [here](https://www.firebirdnews.org/docs/papers/GDSDBProtocol.html).

Most of the messages are only sent by the client, and the server response is a `op_response` most of the time, returning a "handle" (database, transaction or statement handle, for example), and "objectId" (only used in the `rsfbclient-rust` on blob operations, as the "blobId"), a buffer with is used to return data, and the "StatusVector" which says if there was any error and what error occurred.

About the BLR, i could not find much info about it, so i don't know for sure how it works, however it is used in the crate this way:
It begins with a version (Version 5 used), a "begin" byte and a "message" byte, as it is used to send a message with the data types to the firebird server, and then a list of the parameter types, followed by a "END" and "EOC" bytes before the end.

[XDR]: https://en.wikipedia.org/wiki/External_Data_Representation

**Comment by jairinhohw** [comment]
>     * [ ]  In `rsfbclient-rust` are there any choices being made about communicating with the remote side? or is the wire protocol so tightly specified that there's really only ever one valid sequence of interaction? Does `rsfbclient-rust` try to match the choices of some other client?

There is not much room for choice in the protocol that i know of. The only ones i know is some of the messages that have a "2" variant ("op_create_blob2", "op_exec_immediate2", "op_execute2") that behave a little differently.

For example, the "op_create_blob2" allows to pass a "ParameterBuffer", but i don't know what parameters can be sent and their uses, so i just use the "op_create_blob" message.

The "op_execute2" can only be used for statements that return data and works like a "op_execute" + "op_fetch", so i did not use it for simplicity.

**Comment by jairinhohw** [comment]
>     * [ ]  In Firebird source, what parts of their code turn into `fbclient.so/dll` (in new and in older versions)? what is the exact relationship between standard `ibase.h` and the Firebird Remote / YValve source?

I'm not well versed in C++, so don't really know how to answer this, but the header file used seems to be [this one](https://code.woboq.org/firebird/firebird/src/jrd/ibase.h.html).

**Comment by fernandobatels** [comment]
> [ ] In Firebird source, what parts of their code turn into `fbclient.so/dll` (in new and in older versions)? what is the exact relationship between standard `ibase.h` and the Firebird Remote / YValve source?

This is a good question. The one official [source code guide](https://www.firebirdsql.org/en/source-code-guide/) are empty. I'm trying find something in the [firebird-devel](https://www.mail-archive.com/firebird-devel@lists.sourceforge.net/)
