### ISSUE TITLE
Cross Language Object Oriented Programming (cloop) tool

### ISSUE THREAD

**Issue by afsmi** [fernandobatels/rsfbclient#65]
https://github.com/asfernandes/cloop/

It is used to process [this Interface Description Language file](https://github.com/FirebirdSQL/firebird/blob/6c61b48c1fd4a4799385811cdb2fa0acb1691a47/src/include/firebird/FirebirdInterface.idl) into different programming languages. It appears to be used in official Firebird build scripts

Should we consider making a rust output generator?
We could also potentially translate the c++ code of this tool? (the c++ is not so complicated) I don't know if this is helpful or not.

Maybe someone wants to discuss it with the maintainer (who is also one of the primary contributors to the [official FirebirdSQL github project](https://github.com/FirebirdSQL) )

**Comment by fernandobatels** [comment]
I think this is not very helpful now. I don't see a real utilization of this approach for us. 

Curiosity: I an few weeks ago, when i had shared the lib into firebird-devel maillist, one of fb mainters ask about this same tool.

**Comment by afsmi** [comment]
Seems like we won't do anything with it for now.
