### ISSUE TITLE
Make the main crate easier to source-patch

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#66]
Until we've fully settled on on design choices of the main api and its implementation, it would be useful to make it easier to substitute other source (say using cargo's [`[patch]`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) facility) without having to worry too much about the content of  specific files in `src/`.

Currently `src/lib.rs` mixes together re-exports, `cfg` flags, and exports of crate-internal paths.
Generally if i'm patching, I want to keep the re-exports of other crates, but replace internal modules.

@fernandobatels originally suggested to me that we could move the main source into a different crate, but after I thought about it more I think a simpler  way is just to organize modules, visibility specifiers and re-exports more carefully.

in particular, we should move all crate-internal source into sub-modules. I propose just a single sub-module for now. Let's say for now it's called `default_impl`.
then `lib.rs` and `default_impl.rs` become the only files in `src/` ([as opposed to using `mod.rs` in a subdirectory](https://doc.rust-lang.org/reference/items/modules.html#module-source-filenames)) and everything else is in `src/default_impl/`. This is easy to patch over.

all crate-internal visibility should be controlled by `default_impl.rs`, this includes both inter-module visibility as well as `pub use` declarations for exporting and aliasing internals of the crate

`lib.rs` would consist only of re-exports of external crate paths, as well as
```
mod default_impl;
pub use default_impl::*;
```

on a related note we should be careful about how we use [`crate::` -prefixed imports](https://github.com/fernandobatels/rsfbclient/blob/5dbff8d8b150cf53a4a84ceaf7c805556cefb121/src/connection/stmt_cache.rs#L10) in internal modules since these can break easily when things get moved around.
`super::` is advantageous because it allows different kinds of visibility to be controlled almost entirely from module roots (by which i mean the equivalent of `mod.rs` or `default_impl.rs` here), and when you're feeling lazy you can just do `super::*` in all of the modules to use a common set of items which are `use`d in the module root.

what do you think?
if you are ok with this proposal, do you have any suggestions for the module name? i don't really care in the end but I did not try very hard with the name "default_impl"

**Comment by fernandobatels** [comment]
> what do you think?

I liked. The 'sub-module' approach is really more attractive that a new sub-crate, thinking in breaking changes. 

> do you have any suggestions for the module name?

I see the main 'crate' as an interface for use the lib, so we can call this a 'default_interface', or some other abbreviation. What do you think? 

> on a related note we should be careful about how we use crate:: -prefixed imports in internal modules since these can break easily when things get moved around.

We can fix this in this issue too, directly in the PR, to avoid future problems
