### ISSUE TITLE
Connection builder

### ISSUE THREAD

**Issue by fernandobatels** [fernandobatels/rsfbclient#7]
I'm thinking in make a "ConnectionBuilder" for start a new connection instead of the 'connection' and 'connection_local'. Like in the [sled](https://docs.rs/sled/0.33.0/sled/struct.Config.html).

In our case we will use this for set the db dialect and more. Something like:
```
let mut conn = ConnectionBuilder::default()
     .host("localhost")
     .user("sysdba")
     .dialect(Dialect::D3)
     .connect()?;
```

What you think @jairinhohw ?

**Comment by jairinhohw** [comment]
I think it will be very good.

Another way to implement this is the "init struct pattern" as described [here]. It can be used if all fields have a default and there is no need for per field validation. It can look like this:
```rust
let conn = Connection::new(Options {
    host: "localhost".to_string(),
    user: "sysdba".to_string(),
    dialect: Dialect::D3,
    .. Default::default(),
})?;
```
But i do not know if is possible to remove the `to_string()`s with this approach, so maybe It's better the other way.

The article describes a "hack" to make the struct non exhaustive, but there is now a `#[non_exhaustive]` attr ([link]).

[here]: https://xaeroxe.github.io/init-struct-pattern/
[link]: https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html#non_exhaustive-structs-enums-and-variants
