### ISSUE TITLE
Rust parser/deserializer for Firebird DSQL

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#70]
With a parser, we could do compile-time checks on DSQL and statement parameters, and more.

Some resources (for commit permalinks, make sure to check the latest versions) 
* [dsql compiler code in Firebird](https://github.com/FirebirdSQL/firebird/tree/92830d4c243354a889419da14cda4c0db1374b8c/src/dsql)
  * [the main grammar for Firebird DSQL, in btyacc format](https://github.com/FirebirdSQL/firebird/blob/e9f3eb360db41ddff27fa419b908876be0d2daa5/src/dsql/parse.y)
  * [woboq code explorer version](https://code.woboq.org/firebird/firebird/src/dsql/)
  * [quick description from the fb-devel list. saved in wayback machine.](https://www.mail-archive.com/firebird-devel@lists.sourceforge.net/msg11418.html)
  * [a bit of commentary by asfernandes from 2012. saved in wayback machine.](https://asfernandes.github.io/2012/04/26/dsqlblr-compilers-internals.html)
  * [Tokens for the lexer?](https://github.com/FirebirdSQL/firebird/blob/92830d4c243354a889419da14cda4c0db1374b8c/src/common/keywords.cpp)
  * [`keywords.cpp` again, but indexed by firebird version](https://github.com/mrotteveel/firebird-reserved-words/tree/fe78fa17aab353ab80649dd339371347fc3c4665/keywords/firebird)

* [SQL standards conformance table for Firebird](https://firebirdsql.org/en/sql-conformance/)
* [some people dying for Firebird DSQL tooling support. ](https://youtrack.jetbrains.com/issue/DBE-3650)

Do any major database-agnostic DB libraries (ie something like Diesel) expect parsers/deserializers or their output to implement specific traits? I suspect so, but I don't know.

**Comment by fernandobatels** [comment]
I think that I got you point, but you have some examples of this idea in rust?

 I have 0 experience with DSQL.

**Comment by fernandobatels** [comment]
> I have 0 experience with DSQL.

My mistake. I confounded the DSQL with a OO API or some 'query builder' feature.

Anyway, how this will works in the lib or whats is the use-case?
