### ISSUE TITLE
CI: allow method to disable workflows for draft PRs/other situations

### ISSUE THREAD

**Issue by afsmi** [fernandobatels/rsfbclient#76]
Sometimes on drafts we know tests won't pass, or we're just making little changes. Check annotations can be noisy and we're just spinning up a bunch of docker containers for nothing and using the free minutes (2000/month)

I can think of different ways to do this:
* using `if: github.event.pull_request.draft == false` on all jobs (this might be a bit [broken](https://github.community/t/status-of-workflows-with-no-running-jobs/16782) but there's workarounds)
* using special branches as the merge target (complication: keep them synchronized with master only)
* using labels

Some ways make it so it is still hard or impossible to accidentally get merged later without testing. these tend to be more complicated.

Other ways are just manual overrides that can be used in any situation including drafts but also regular PRs. these tend to be simpler.

@fernandobatels I think it's just a question of whether you as repository owner are ok with this or not since you are doing the merging. It's always possible to make an issue referencing changes in a fork instead of making a draft pr here.

if you're interested I can provide more details on different approaches

**Comment by fernandobatels** [comment]
Good question. I also don't like the 'always mode' of our CI. Maybe using a label like 'no-ci' will solve the problem. 

In the scenario: 

- I open a PR/draft with 'no-ci' label
   - My push's won't go trigger the CI
- I finish my changes
- I remove the 'no-ci' label

What happen next? I can make some event to trigger the CI other than a push?
