### ISSUE TITLE
Diesel support

### ISSUE THREAD

**Issue by fernandobatels** [fernandobatels/rsfbclient#85]
I'm thinking in implement a Firebird backend for [diesel](https://diesel.rs) ORM. Honestly, I've never used the diesel before, but I have good feelings about this tool.

So, some questions come to me:

- This backend can be implemented here in a `rsfbcleint-diesel` crate?
- Do you know any guide for this implementation? I couldn't find anything, so I'm using the [pg backend](https://github.com/diesel-rs/diesel/blob/master/diesel/src/pg) as example.

**Comment by fernandobatels** [comment]
Ping @afsmi @jairinhohw

**Comment by afsmi** [comment]
i think it would be good to have as a separate crate at the start. It seems that there are a lot of structs and traits to implement

Some aspects could be in the main crate or core, though. For example structs for different clause fragments (`AND`, `OR`, `ON` etc) and builder methods. A lightweight builder/serializer for those could be helpful to have without other parts of diesel

lt may end up forcing some changes in our other crates to do some things 'the diesel way'.

They have a discourse and a gitter, i would ask there about how to proceed

quick links:
* https://gitter.im/diesel-rs/diesel
* https://discourse.diesel.rs/
* https://github.com/diesel-rs/diesel

**Comment by juarezr** [comment]
Adding [SQLX](https://github.com/launchbadge/sqlx) to the wish list. :+1:

**Comment by fernandobatels** [comment]
> Adding [SQLX](https://github.com/launchbadge/sqlx) to the wish list. +1

Can you help with the implementation?

**Comment by juarezr** [comment]
> > Adding [SQLX](https://github.com/launchbadge/sqlx) to the wish list. +1
> 
> Can you help with the implementation?

When I got some spare time I'll try.

But time have been scarce lately. :smiley:
