### ISSUE TITLE
Consider switching to some form of outparams in FirebirdClient fetch results

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#88]
Instead of doing this in our clients

```
/// Data associated with a prepared statement
pub struct StmtHandleData {
    /// Statement handle
    raw_stmt_handle: ibase::isc_stmt_handle,
    /// Output xsqlda
    xsqlda: XSqlDa,
    /// Buffers for the output xsqlda
    col_buffers: Vec<ColumnBuffer>,
}
```

and this in core API

```
fn fetch(
    &mut self,
    db_handle: &mut Self::DbHandle,
    tr_handle: &mut Self::TrHandle,
    stmt_handle: &mut Self::StmtHandle,
) -> Result<Option<Vec<Column>>, FbError>;
```

what if we had this in our clients (as the stmt handle used to be)

```
/// Data associated with a prepared statement
type StmtHandle = ibase::isc_stmt_handle;

pub struct XYZClientRowBuffer {
    //Handle passed along with corresponding buffer
    stmt_handle: StmtHandle,
    /// Output xsqlda
    xsqlda: XSqlDa,
    /// Buffers for the output xsqlda
    col_buffers: Vec<ColumnBuffer>
}
```

and this in our core api:

```
fn get_buffer(
    &mut self,
    stmt_handle: &mut Self::StmtHandle,
    row_count: usize,
) -> Result<Self::RowBuffer, FbError>;

fn fetch(
    &mut self,
    db_handle: &mut Self::DbHandle,
    tr_handle: &mut Self::TrHandle,
    result_buffer: &mut Self::RowBuffer,
) -> Result<FetchStatus, FbError>;

```

in this example `Self::RowBuffer` is `XYZClientRowBuffer`, which has a trait bound to help move/copy the contents of the buffer out, which would be used in `FromRow::try_from()`.

Actually this could be quite useful for testing: A mock buffer that succeeds for any FromRow, returning fake data

Some possible variations:
* prepare_statement returns a a transparent enum with only some variants containing a buffer or just the xsqlda in addition to the statement handle. StmtType could be placed in there too, either transparently or opaquely.
* The client itself manages the buffers automatically for open cursors, and `get_buffer` (or maybe just `fetch`) return a handle to it that can be used to copy/move the data out.

your thoughts on this?

**Comment by fernandobatels** [comment]
> your thoughts on this?

I liked. Do you will implement this?

> Actually this could be quite useful for testing

what scenarios do you have in mind?

**Comment by afsmi** [comment]
Ok, I will implement this eventually.
Actually I have a really big set of changes right now that I am trying to split up into smaller parts.

As for usefulness in testing:
On my todo list is a mock `FirebirdClient` that we can use to do a lot of tests (and other things) without a real database.
The issue with returning `Vec<Column>`  is we have to decide the value of the `Column`s at the time when `fetch` is called.
But what I want is to be able to do it when `FromRow::try_from()` is called later, so it would be in a sense a "virtual buffer"

**Comment by jairinhohw** [comment]
I'm not against it, however there is some things to consider, and i think this would make using this buffer a little awkward.
* The `XYZClientRowBuffer` would need to store a mutable reference to the `StmtHandle`, as it cannot own it.
* It would be possible to try getting data out of the buffer with `FromRow::try_from()` before the buffer has data (before calling `fetch`), so this need to be handled (maybe an error when calling `FromRow::try_from()`).
* It would be possible to try getting the data more than once after a call to `fetch`, so the `FromRow::try_from()` would need to return an error on the second try or return the same data multiple times.
* For the case of the `pure_rust` implementation, there is no buffer, so the columns would need to be moved in the `XYZClientRowBuffer` when calling `fetch` and out again when calling `FromRow::try_from()` the first time, then error on calling a second time to allow not adding any unnecessary cloning of the data, so would need something in the `XYZClientRowBuffer` to tell if there is data stored in it (would also work for the second point).

Those things are not that important, as the API is not meant to be used by end users, so not much of a problem actualy.
