### ISSUE TITLE
Connection strings

### ISSUE THREAD

**Issue by fernandobatels** [fernandobatels/rsfbclient#90]
In the [diesel pr](#90) I need create the connection using a string, because of [this trait](https://docs.diesel.rs/master/diesel/connection/trait.Connection.html#tymethod.establish) requirement.

So, I have two issues:

- What string format are we going to use?
    - Firebird use [some formats](https://www.ibphoenix.com/files/ConnectionStrings_Fb3.pdf) in this native client, but we also have [others formats](https://www.connectionstrings.com/firebird/)
- Would that be an eligible resource for the main crate?
    - We can create the string support directly in the main crate or only in the diesel support. What do you think?

**Comment by fernandobatels** [comment]
Ping @jairinhohw @afsmi

**Comment by afsmi** [comment]
> * What string format are we going to use?
>   * Firebird use [some formats](https://www.ibphoenix.com/files/ConnectionStrings_Fb3.pdf) in this native client, but we also have [others formats](https://www.connectionstrings.com/firebird/)

how about: pick any, but add a prefix for now in case we change our mind, like
* `standard:host=127.0.0.1;user=...` if it is the officially documented one
* then, in a year maybe we decide to add `json: ...`

etc. careful about whitespaces. Might be nice to look for quotes or escape characters around/in windows file paths, for example

> * Would that be an eligible resource for the main crate?
>   * We can create the string support directly in the main crate or only in the diesel support. What do you think?

I imagine `establish` will need to create an `FirebirdClient::AttachmentConfig`, which is implementation-dependent, so I think it should be part of `native`/`pure-rust` actually, otherwise you will just end up coupling code across crate/module boundaries in a non-generic way, like builders do, which imo is not good.

Some variations:
* Some helper functions for parsing formats we know about could go in `core`, maybe in a new `helpers.rs` or `extensions.rs` module, to be reused by implementations (i almost did this when i touched builders previously)
* Add the trait bound `TryFrom<&str>` for `FirebirdClientDbOps::AttachmentConfig`, either:
  * in core, as a bound on `AttachmentConfig` inside the `FirebirdClientDbOps` trait
  * in your impl for `diesel::connection::Connection`. pseudocode:

    ```
    impl<C> diesel::connection::Connection ....
    where
       C: FirebirdClient,
       <C as FirebirdClientDbOps>::AttachmentConfig : TryFrom<&str>,
     {
       fn establish ... {
          ...
          let attachment_config = <C as FirebirdClientDbOps>::AttachmentConfig.try_from(&connstring);
          match attachment_config {
          ...
       } 
     }
    ```

**Comment by jairinhohw** [comment]
At least for the diesel connection string, i think we should make it similar to the existing postgres / mysql connection strings.
Example.: `firebird://username:password@localhost:3050/database_name`

I think it can be used in the builders too, as a alternative way to complete the host / port  / user / pass / db_name.

**Comment by jairinhohw** [comment]
This has the added benefit of being easy to parse with an `URL` parser, additional arguments can be passed as query parameters.
Example: `firebird://username:password@localhost:3050/database_name?dialect=3&pure_rust=true`

**Comment by fernandobatels** [comment]
Ok, I will implement this using a prefix. The 'diesel style', in this case.
Using the prefix, in the future we can provide the others firebird string connection support, like the `INET`.

**Comment by fernandobatels** [comment]
> > * What string format are we going to use?
> >   
> >   * Firebird use [some formats](https://www.ibphoenix.com/files/ConnectionStrings_Fb3.pdf) in this native client, but we also have [others formats](https://www.connectionstrings.com/firebird/)
> 
> how about: pick any, but add a prefix for now in case we change our mind, like
> 
>     * `standard:host=127.0.0.1;user=...` if it is the officially documented one
> 
>     * then, later maybe we decide to add `json: ...` (not that I expect to add json support, it's just an example)
> 
> 
> etc. careful about whitespaces. Might be nice to look for quotes or escape characters and strip spaces elsewhere
> 
> > * Would that be an eligible resource for the main crate?
> >   
> >   * We can create the string support directly in the main crate or only in the diesel support. What do you think?
> 
> I imagine `establish` will need to create an `FirebirdClient::AttachmentConfig`, which is implementation-dependent, so I think it should be part of `native`/`pure-rust` actually, otherwise you will just end up coupling code across crate/module boundaries in a non-generic way, like builders do, which imo is not good.
> 
> Some variations:
> 
>     * Some helper functions for parsing formats we know about could go in `core`, maybe in a new `helpers.rs` or `extensions.rs` module, to be reused by implementations (i almost did this when i touched builders previously)
> 
>     * Add the trait bound `TryFrom<&str>` for `FirebirdClientDbOps::AttachmentConfig`, either:
>       
>       * in core, as a bound on `AttachmentConfig` inside the `FirebirdClientDbOps` trait
>       * in your impl for `diesel::connection::Connection`. pseudocode:
>         ```
>         impl<C> diesel::connection::Connection ....
>         where
>            C: FirebirdClient,
>            <C as FirebirdClientDbOps>::AttachmentConfig : TryFrom<&str>,
>          {
>            fn establish ... {
>               ...
>               let attachment_config : Result<<C as FirebirdClientDbOps>::AttachmentConfig, FbError> = connstring.try_into();
>               match attachment_config {
>               ...
>            } 
>          }
>         ```
>         
>         
>         actually if you did it this way you can be lazy and defer implementing it in `native`/`pure_rust` at all, for now, and your code will still typecheck :)

I had tried work in this idea(``TryFrom to FirebirdClientDbOps``), but we would still need provide a valid type client. 

Therefore, to simplify the user utilization, I will use the ConnectionBuilder instead. The result will be something like this:

```
rsfbclient::builder_native()
    .from_str("firebird://username:password@localhost:3050/database_name?dialect=3")?
    .connect()
```
