### ISSUE TITLE
the trait `FromRow` is not implemented for ....

### ISSUE THREAD

**Issue by AndreiTS** [fernandobatels/rsfbclient#95]
What this error means?
![image](https://user-images.githubusercontent.com/13489837/105852357-20e3e600-5fc3-11eb-9d99-d685570d1d8e.png)

I have a custom type holding a tuple with the type of each column from the table:

    type ClienteFields = (String, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<i32>, Option<i32>, Option<i32>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<f64>, Option<f64>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>, Option<i32>, Option<i32>, Option<String>, Option<f64>, Option<f64>, Option<String>, Option<String>, Option<String>, Option<String>, Option<String>);

And I'm using it like this:

`    let rows = conn.query_iter("SELECT * FROM C000007", ())?;

    for row in rows {
        let row_data: ClienteFields = row.unwrap();

        println!("{:?}", row_data.0);
    }
`

**Comment by AndreiTS** [comment]
Table structure: https://pastebin.com/gcsEjvAs

**Comment by fernandobatels** [comment]
> What this error means?

You have too many columns. Like 101. At this moment, we only implement the 'FromRow' [until 26](https://docs.rs/rsfbclient/0.14.0/rsfbclient/trait.FromRow.html#impl-FromRow-for-(L%2C%20M%2C%20N%2C%20O%2C%20P%2C%20Q%2C%20R%2C%20S%2C%20T%2C%20U%2C%20V%2C%20W%2C%20X%2C%20Y%2C%20Z))

**Comment by fernandobatels** [comment]
You can use the [Row](https://docs.rs/rsfbclient/0.14.0/rsfbclient/struct.Row.html) struct instead and iterate over your columns.

**Comment by fernandobatels** [comment]
If you need a structured row, you can use the `diesel`. We are [still working  on this implementation](https://github.com/fernandobatels/rsfbclient/pull/86), but you can already use for tests.

**Comment by AndreiTS** [comment]
> You can use the [Row](https://docs.rs/rsfbclient/0.14.0/rsfbclient/struct.Row.html) struct instead and iterate over your columns.

Can you give me an example?

**Comment by fernandobatels** [comment]
> > You can use the [Row](https://docs.rs/rsfbclient/0.14.0/rsfbclient/struct.Row.html) struct instead and iterate over your columns.
> 
> Can you give me an example?

Yes. [Here](https://github.com/fernandobatels/rsfbclient/blob/master/examples/namedcolumns_select.rs#L46).

```
 let rows: Vec<Row> = conn.query("select test.*, 10 as extra from test", ())?;

  for row in rows {
      println!("------------------------------------");

      for col in row.cols {
          println!("{}: {:?}", col.name, col.value);
      }
  }
```

**Comment by AndreiTS** [comment]
Thanks
