### ISSUE TITLE
[feature request] New crate as rd2d adaptor

### ISSUE THREAD

**Issue by silvioprog** [fernandobatels/rsfbclient#97]
Hi friends.

What do you think about to isolate the [pool implementation](https://raw.githubusercontent.com/fernandobatels/rsfbclient/f086b7677a33fd0af77a732ff1eb51ba75743e00/src/connection/pool.rs) as a new crate? It would be useful to publish the `FirebirdConnectionManager` as a new r2d2 adapter at their adapters list: [r2d2#adapters](https://github.com/sfackler/r2d2#r2d2). 🙂

cheers

Refs:

- https://github.com/sfackler/r2d2-postgres
- https://github.com/outersky/r2d2-mysql
- https://github.com/ivanceras/r2d2-sqlite
- https://github.com/rursprung/r2d2-oracle

**Comment by fernandobatels** [comment]
I agree with this. And you @jairinhohw ?

**Comment by jairinhohw** [comment]
Agreed.

**Comment by fernandobatels** [comment]
Can you implement, @silvioprog?

**Comment by silvioprog** [comment]
@fernandobatels Yes, I can. 🙂 I have a draft with some build issues. I'm going to ask some questions via Telegram group ...
